### PR TITLE
Rename the productImageLinks field to imageLinks

### PR DESCRIPTION
**Pull request by snowteamer**
Related to #30

### CODE REVIEW

**Comment by Twaha-Rahman** [comment]
When you're finished with the PR, mention me.

**Comment by snowteamer** [comment]
Should the `bannerImageLink` field in the Banner API also renamed to `imageLink`?

**Comment by Twaha-Rahman** [comment]
> Should the `bannerImageLink` field in the Banner API also renamed to `imageLink`?
> @Twaha-Rahman

Let's keep this as is.

**Comment by Twaha-Rahman** [comment]
@snowteamer  Are we ready for this PR?

**Comment by snowteamer** [comment]
I think so, but you might have to resolve a small conflict due to Prettier's reformatting

**Comment by Twaha-Rahman** [comment]
> I think so, but you might have to resolve a small conflict due to Prettier's reformatting @Twaha-Rahman

No worries.

**Pull request merged**
