### PR TITLE
Rename productName field to name

### PR DESCRIPTION
**Pull request by snowteamer**
Related to #23

### CODE REVIEW

**Comment by magnus195** [comment]
Looks good

**Comment by Twaha-Rahman** [comment]
@snowteamer You'll have to update the docs too. Otherwise there'll be inconsistency.

**Comment by snowteamer** [comment]
You're right, so I've modified BACKEND_API.md, but then I could not find any other occurence of `productName`. Is there any?

**Comment by Twaha-Rahman** [comment]
If you're using VSCode, you can use the `Search` feature (Search icon on the left side) to search for any occurrences of `productName`. AFAIK there isn't any but there's no harm in double-checking ;)

**Comment by snowteamer** [comment]
I did a quick `git grep` in the CLI, hope it's enough :)

**Comment by Twaha-Rahman** [comment]
Isn't there another keys called `productId` and `productImageLinks`, what are we going to do with those? I think we should change the latter and keep the former, what do you say?

**Comment by snowteamer** [comment]
I agree on `productImageLinks`; I am a bit less sure on `productId`, which is why I opened #28 to discuss it.

**Comment by Twaha-Rahman** [comment]
I think we'll keep the `productId` as it is for now. We'll discuss about it after this PR.

**Pull request merged**
